name: Pull and Test Rulesets with Docker

on:
  push:
    branches: [ master, rc ]
  workflow_dispatch:

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/midas-base-testing:latest

      - name: Run Tests with Midas
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/c/lints:/app/rules \
            -v ${{ github.workspace }}/c/lints/snippets:/app/scan \
            midas-base-testing | tee midas.log

      - name: Capture Output
        run: |
          echo "Midas output:"
          cat midas.log